import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
// Note: AppLocalizations is generated by 'flutter gen-l10n'
// import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:aqar_morocco_mobile/core/theme/app_theme.dart';
import 'package:aqar_morocco_mobile/providers/locale_provider.dart';
import 'package:aqar_morocco_mobile/providers/auth_provider.dart';
import 'package:aqar_morocco_mobile/providers/listings_provider.dart';
import 'package:aqar_morocco_mobile/providers/visit_provider.dart';
import 'package:aqar_morocco_mobile/providers/chat_provider.dart';
import 'package:aqar_morocco_mobile/providers/notification_provider.dart';
import 'package:aqar_morocco_mobile/ui/screens/splash/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => LocaleProvider()),
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ListingsProvider()),
        ChangeNotifierProvider(create: (_) => VisitProvider()),
        ChangeNotifierProvider(create: (_) => ChatProvider()),
        ChangeNotifierProvider(create: (_) => NotificationProvider()),
      ],
      child: const AqarMoroccoApp(),
    ),
  );
}

class AqarMoroccoApp extends StatelessWidget {
  const AqarMoroccoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<LocaleProvider>(
      builder: (context, provider, _) {
        return MaterialApp(
          title: 'Aqar Morocco',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.darkTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: ThemeMode.dark,
          locale: provider.locale,
          localizationsDelegates: const [
            // AppLocalizations.delegate, // Uncomment once generated
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [
            Locale('fr'),
            Locale('ar'),
            Locale('en'),
          ],
          home: const SplashScreen(),
        );
      },
    );
  }
}
