import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:aqar_morocco_mobile/providers/locale_provider.dart';

extension Localizer on BuildContext {
  String l(String key) {
    final locale = watch<LocaleProvider>().locale.languageCode;
    return _translations[locale]?[key] ?? _translations['fr']?[key] ?? key;
  }

  static const _translations = {
    'fr': {
      'home': 'Accueil',
      'search': 'Rechercher',
      'favorites': 'Favoris',
      'messages': 'Messages',
      'profile': 'Profil',
      'welcome_dream': 'Trouvez votre\nmaison de rêve',
      'hello': 'Bonjour',
      'search_hint': 'Où voulez-vous habiter ?',
      'search_hint_alt': 'Rechercher ville, quartier...',
      'new_maroc': 'Nouveautés au Maroc',
      'all_listings': 'Toutes les annonces',
      'buy': 'Acheter',
      'rent': 'Louer',
      'my_profile': 'Mon Profil',
      'please_login': 'Veuillez vous connecter',
      'buy_role': 'Acheter',
      'sale_role': 'Vendre',
      'rent_role': 'Louer',
      'to_sale': 'À VENDRE',
      'to_rent': 'À LOUER',
      'lease_role': 'Mettre en location',
      'agency_role': 'Agence',
      'verified_acc': 'Compte vérifié',
      'unverified_acc': 'Compte non vérifié',
      'listing_details': 'Détails de la propriété',
      'description': 'Description',
      'location': 'Localisation',
      'contact_owner': 'Contacter l\'annonceur',
      'request_visit': 'Demander une visite',
      'bedrooms': 'Chambres',
      'bathrooms': 'Salles de bain',
      'area': 'Surface',
      'm2': 'm²',
      'price_mad': 'MAD',
      'agent_imb': 'Agent Immobilier',
      'message': 'Message',
      'contact': 'Contact',
      'ch': 'ch',
      'sdb': 'sdb',
      'no_chats': 'Aucune conversation',
      'write_message': 'Écrivez un message...',
      'send': 'Envoyer',
      'moments_ago': 'À l\'instant',
      'min_ago': 'min',
      'online': 'En ligne',
      'welcome_aqar': 'Propulsez votre recherche immobilière au Maroc.',
      'login_header': 'Se connecter',
      'login_to_continue': 'Se connecter pour continuer',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'login': 'Se connecter',
      'no_account': 'Pas encore de compte ?',
      'register': 'S\'inscrire',
      'create_account': 'Créer un compte',
      'full_name': 'Nom complet',
      'already_account': 'Déjà un compte ?',
      'already_account_link': 'Vous avez déjà un compte? ',
      'register_error': 'Erreur lors de l\'inscription',
      'phone': 'Téléphone',
      'confirm_password': 'Confirmer le mot de passe',
      'no_account_link': 'Pas encore de compte? ',
      'create_account_link': 'Créer un compte',
      'none_found': 'Aucune annonce trouvée',
      'guest': 'Invité',
      'app_verified': 'Vérifié par Aqar Morocco',
      'apartment': 'Appartement',
      'villa': 'Villa',
      'riad': 'Riad',
      'land': 'Terrain',
      'name_required': 'Le nom est obligatoire',
      'min_3_chars': 'Minimum 3 caractères',
      'email_required': 'L\'email est obligatoire',
      'email_invalid': 'Email invalide',
      'phone_required': 'Le téléphone est obligatoire',
      'phone_invalid': 'Numéro marocain invalide',
      'password_required': 'Le mot de passe est obligatoire',
      'min_8_chars': 'Minimum 8 caractères',
      'password_mismatch': 'Les mots de passe ne correspondent pas',
      'invalid_creds': 'Identifiants incorrects',
    },
    'ar': {
      'home': 'الرئيسية',
      'search': 'بحث',
      'favorites': 'المفضلة',
      'messages': 'الرسائل',
      'profile': 'الحساب',
      'welcome_dream': 'ابحث عن\nمنزل أحلامك',
      'hello': 'مرحباً',
      'search_hint': 'أين تود السكن؟',
      'search_hint_alt': 'ابحث عن مدينة، حي...',
      'new_maroc': 'جديد المغرب',
      'all_listings': 'كل الإعلانات',
      'buy': 'شراء',
      'rent': 'كراء',
      'my_profile': 'حسابي',
      'please_login': 'يرجى تسجيل الدخول',
      'buy_role': 'شراء',
      'sell_role': 'بيع',
      'rent_role': 'كراء',
      'to_sale': 'للبيع',
      'to_rent': 'للكراء',
      'lease_role': 'تأجير',
      'agency_role': 'وكالة',
      'verified_acc': 'حساب موثق',
      'unverified_acc': 'حساب غير موثق',
      'listing_details': 'تفاصيل العقار',
      'description': 'الوصف',
      'location': 'الموقع',
      'contact_owner': 'الاتصال بالمعلن',
      'request_visit': 'طلب زيارة',
      'bedrooms': 'غرف نوم',
      'bathrooms': 'حمامات',
      'area': 'المساحة',
      'm2': 'متر مربع',
      'price_mad': 'درهم',
      'agent_imb': 'وكيل عقاري',
      'message': 'رسالة',
      'contact': 'اتصال',
      'ch': 'غرفة',
      'sdb': 'حمام',
      'no_chats': 'لا توجد محادثات',
      'write_message': 'اكتب رسالة...',
      'send': 'إرسال',
      'moments_ago': 'الآن',
      'min_ago': 'د',
      'online': 'متصل',
      'welcome_aqar': 'ارفع مستوى بحثك العقاري في المغرب.',
      'login_header': 'تسجيل الدخول',
      'login_to_continue': 'تسجيل الدخول للاستمرار',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'login': 'تسجيل الدخول',
      'no_account': 'ليس لديك حساب؟',
      'register': 'إنشاء حساب',
      'create_account': 'إنشاء حساب الجديد',
      'full_name': 'الاسم الكامل',
      'already_account': 'لديك حساب بالفعل؟',
      'already_account_link': 'هل لديك حساب بالفعل؟ ',
      'register_error': 'فشل التسجيل',
      'phone': 'الهاتف',
      'confirm_password': 'تأكيد كلمة المرور',
      'no_account_link': 'ليس لديك حساب؟ ',
      'create_account_link': 'إنشاء حساب الجديد',
      'none_found': 'لم يتم العثور على أي إعلانات',
      'guest': 'زائر',
      'app_verified': 'موثق من طرف عقار المغرب',
      'apartment': 'شقة',
      'villa': 'فيلا',
      'riad': 'رياض',
      'land': 'أرض',
      'name_required': 'الاسم مطلوب',
      'min_3_chars': '3 أحرف على الأقل',
      'email_required': 'البريد الإلكتروني مطلوب',
      'email_invalid': 'بريد إلكتروني غير صالح',
      'phone_required': 'رقم الهاتف مطلوب',
      'phone_invalid': 'رقم مغربي غير صالح',
      'password_required': 'كلمة المرور مطلوبة',
      'min_8_chars': '8 أحرف على الأقل',
      'password_mismatch': 'كلمات المرور غير متطابقة',
      'invalid_creds': 'بيانات الدخول غير صحيحة',
    }
  };
}
